#uruchamianie innego profilu niż domyślny w buildzie odbywa się za pomocą komendy po uruchomieniu jara: --spring.profiles.active=dev
#dodatkowo ustawienie np portu: --server.port=3000

app:
  useMockRepository: false

logging:
  level:
    root: INFO

server:
  error:
    include-message: always
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:h2:mem:testdb-dev-environment
    driver-class-name: org.h2.Driver
    username: sa-dev
    password: sa-dev
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-dev
  main:
    banner-mode: off

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - prometheus